// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWMJuSaWKfcUc_9MU3Pkn73IFRh2Nk5bY',
    appId: '1:1054917317493:web:b57ece8c1f8efd155ef93c',
    messagingSenderId: '1054917317493',
    projectId: 'zeppo-app',
    authDomain: 'zeppo-app.firebaseapp.com',
    storageBucket: 'zeppo-app.firebasestorage.app',
    measurementId: 'G-VYXMT5G772',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAui2AXoU_lS_kI8owsJtzOCGe43yQmjvg',
    appId: '1:1054917317493:android:1482a30a3f901a575ef93c',
    messagingSenderId: '1054917317493',
    projectId: 'zeppo-app',
    storageBucket: 'zeppo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC59-MlciHtW93XAVLr7qKNS8CI8AvnWOY',
    appId: '1:1054917317493:ios:9af221d9a2f435305ef93c',
    messagingSenderId: '1054917317493',
    projectId: 'zeppo-app',
    storageBucket: 'zeppo-app.firebasestorage.app',
    iosBundleId: 'com.invento.zeppo',
  );
}
